// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCciwLwjwjshSak5CrAgYzdhPWwMbL_otc',
    appId: '1:914173587363:android:7b806876c7b4a9c8d2f416',
    messagingSenderId: '914173587363',
    projectId: 'sales-management-1e397',
    storageBucket: 'sales-management-1e397.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxgDsPruCfnVYqhXakJ8PeJBmCTb3ydUA',
    appId: '1:914173587363:ios:3e97247684e2ba3cd2f416',
    messagingSenderId: '914173587363',
    projectId: 'sales-management-1e397',
    storageBucket: 'sales-management-1e397.appspot.com',
    androidClientId: '914173587363-44oqqf3c8u8qs58jr6t9ufnetjflhf6g.apps.googleusercontent.com',
    iosClientId: '914173587363-nnigqdmt44e4s62rkq7dhhmn0baas6qj.apps.googleusercontent.com',
    iosBundleId: 'com.jumbo.RunnerTests',
  );
}
